spring:
  redis:
    port: 6379
    host: localhost
    database: 1
    password:
    timeout: PT5S
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      # 默认的交换机和路由
      exchange: Exchange1
      routing-key: key
      # 30秒
      receive-timeout: 30000

server:
  port: 8081